name: Start New Codebundle
on:
  issues:
    types:
      - opened
jobs:
  codebundle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: fetch issue content
        run: |
          sleep 2 # Wait for issue to be created
          curl -s -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          # force eventual consistency
          sleep 2
          echo "writing to tmp"
          echo "body=$(curl -s -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body')" >> /tmp/issue_content
          echo "checking tmp content"
          cat /tmp/issue_content
      - name: Run Python script
        run: python .github/scripts/main.py /tmp/issue_content
