name: Start New Codebundle
on:
  issues:
    types:
      - opened
jobs:
  codebundle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.ref }}
      - name: fetch issue content
        run: |
          sleep 2 # Wait for issue to be created
          curl -s -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
          # force eventual consistency
          sleep 2
          echo "writing to tmp"
          echo "$(curl -s -H \"Authorization: token ${{ secrets.GITHUB_TOKEN }}\" \
          -H \"Accept: application/vnd.github.v3+json\" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body')" >> /tmp/issue_content
          echo "checking tmp content"
          cat /tmp/issue_content
      - name: Run Python script
        run: python .github/scripts/main.py /tmp/issue_content
      - name: Git Config
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Codebundle Branch
        run: |
          echo "$PWD"
          INIT_DIR=$(echo $PWD)
          pwd
          mkdir -p "INIT_DIR/codebundles/${DIR}"
          cd /tmp/codebundle/
          DIR="./"
          echo "Found directory: $DIR"
          mv "/tmp/codebundle/${DIR}/"* "$INIT_DIR/codebundles/${DIR}/"
          git add "/codebundles/${DIR}/"

          BRANCH="new-${DIR}"
          git checkout -b $BRANCH

          # Test if any git changes are made. If not, bail out and send instruction. 
          if [ -z "$(git diff-index HEAD)" ] 
          then 
              echo "No git changes detected"
              exit 0
          else
              echo "Changes detected. Pushing..."
              git commit -m "Setup new codebundle branch"
              git push --set-upstream origin $BRANCH
          fi

          # Open up a PR
          PR_OUTPUT=$(curl -X POST -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"title\":\"automatic-index-update\",\"head\":\"$BRANCH\",\"base\":\"main\",\"body\":\"automatic-index-update\" }" https://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/pulls)
          PR_LINK=$(echo $PR_OUTPUT | jq '._links.html.href' )
          PR_LINK=$(echo $PR_LINK | tr -d '"')
